version: '3.4'

services:
  salesapi:
    image: salesapi
    build:
      context: .
      dockerfile: Sales.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"